name: CI/CD

on:
  pull_request:
    branches:
      - Dev
  push:
    branches:
      - Test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run unit tests
        run: python -m unittest discover

  approve:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Add 'approved' label
        run: |
          echo "label: approved" >> $GITHUB_EVENT_PATH
  
  generate-docs:
    runs-on: ubuntu-latest

    needs: approve

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set Git Config with Token
        run: |
          git remote rm origin
          git remote add origin https://$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Install pdoc3
        run: pip install pdoc3

      - name: Generate GUI Documentation
        run: pdoc3 --html -o docs task_manager_gui.py

      - name: Generate Backend Documentation
        run: pdoc3 --html -o docs task_manager_backend.py

      - name: Commit and Push Documentation
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs
          git commit -m "Update documentation" || true
          git remote add origin_with_token https://$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git
          git push origin_with_token HEAD:${GITHUB_REF}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}



  deploy:
    runs-on: ubuntu-latest

    needs: approve

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Copy code to Prod branch
        run: git checkout Prod && git merge Test

  build-artifact:
    runs-on: ubuntu-latest

    needs: deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pyinstaller
        run: pip install pyinstaller

      - name: Build artifact
        run: pyinstaller --onefile task_manager_gui.py
